baseURL = "http://msfukui.jp/"
languageCode = "ja_JP"
title = "msfukui's site"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "msfukui"
    description = "Is it a personal blog?"
    githubUsername = "msfukui"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "ruby"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 2

[[menu.icon]]
    url = "mailto:msfukui@gmail.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/msfukui"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/msfukui"
    name = "fab fa-twitter"
    weight = 3
