baseURL = "/"
languagecode = "ja"
defaultcontentlanguage = "ja"
title = "msfukui.page"
theme = "hugo-coder"
googleAnalytics = ""

[markup.highlight]
style = "github-dark"

[params]
    author = "msfukui"
    info = "おおまさのみみはそらのみみ。"
    description = "msfukui's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "/images/msfukui.jpg"
    favicon_16 = "/images/msfukui.ico"
    favicon_32 = "/images/msfukui.ico"
    touchIcon = "/images/msfukui.ico"
    since = 2021
    enableTwemoji = true
    colorScheme = "auto"
    hidecolorschemetoggle = false
    font = "M PLUS Rounded 1c"

[[params.social]]
    name = "github"
    icon = "fa fa-github fa-2x"
    weight = 1
    url = "https://github.com/msfukui"

[[params.social]]
  name = "twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 2
  url = "https://twitter.com/msfukui"

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/slides/"
    name = "Slides"
    weight = 3

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 4

[[menu.main]]
    url = "https://msfukui.hatenablog.com"
    name = "Other"
    weight = 5

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
