baseURL = "/"
languageCode = "ja-jp"
title = "msfukui.page"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "msfukui"
    description = "おおまさのみみはそらのみみ。"
    githubUsername = "msfukui"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "M PLUS Rounded 1c"
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "ruby"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "https://msfukui.hatenablog.com"
    name = "Blog"
    weight = 4

[[menu.main]]
    url = "/slides/"
    name = "Slides"
    weight = 5

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 6

[[menu.icon]]
    url = "https://github.com/msfukui"
    name = "fab fa-github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/msfukui"
    name = "fab fa-twitter"
    weight = 2

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
