name: ghcr-publish

on:
  push:
    branches:
      - main
    paths_ignore:
      - README.md
      - .gitignore
      - exampleSite/**
    tags:
      - v*

env:
  IMAGE_NAME: msfukui.page

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      -
        name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.82.0'
      -
        name: Build contents
        run: hugo --minify
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Login to GitHub Container Registory
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Set docker version tags
        id: tags
        run: |
          REGISTRY="ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}"

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && TAGS="${REGISTRY}:latest"
          [ "$VERSION" != "main" ] && TAGS="${REGISTRY}:latest,${REGISTRY}:$VERSION"

          echo $TAGS

          # Set value to this step's outputs
          echo "::set-output name=name::$TAGS"
      -
        name: Build and push
        id: docker_build_push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.tags.outputs.name }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build_push.outputs.digest }}
